server:
  port: 9999

#阿里druid
spring:
  redis:
    #单机
    # Redis服务器地址
    # host: 192.168.43.33
    # Redis服务器连接端口
    # port: 16379
      # 集群
      #多个节点以逗号分隔
    cluster:
      nodes: 192.168.43.33:7000,192.168.43.33:7001,192.168.43.33:7002,192.168.43.33:7003,192.168.43.33:7004,192.168.43.33:7005
    # Redis服务器连接密码（默认为空）
    password: root
    # Redis数据库索引（默认为0）
    database: 0
    #连接池
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # JDBC 配置
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/film_ticket?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: root

      filters: stat,wall
      #      filters: stat,wall,log4j,config
      #连接池配置
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20



#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # config-location: classpath:mybatis-config.xml
  type-aliases-package: edu.xja.entity



pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
